version: "2"

services:
  hbase:
    build: ./hbase
    container_name: hbase
    volumes:
      - "/tmp/hbase-data:/data-volume"
    ports:
      - 12181:2181
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030 
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - 16379:6379
    networks:
      - back-tier

  postgres:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    environment:
      - DEBUG=false
      - DB_USER=airflow 
      - DB_PASS=airflow
      - DB_NAME=airflow,mytest
    ports:
      - 15432:5432
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  airflow:
    image: puckel/docker-airflow:1.8.1
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    ports:
      - "18080:8080"
    command: webserver 
    networks:
      - back-tier
 
  es:
    image: sebp/elk
    container_name: es
    environment:
      - "CLUSTER_NAME=docker-cluster"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - es-data:/var/lib/elasticsearch
    ports:
      - 19200:9200
      - 15601:5601
      - 15044:5044
    networks:
      - back-tier

volumes:
  es-data:
    driver: local
  postgres-data:

networks:
  back-tier: