version: "2"

services:
  hbase:
    build: ./hbase
    container_name: hbase
    volumes:
      - "/tmp/hbase-data:/data-volume"
    ports:
      - 12181:2181
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030 
    networks:
      - back-tier

  redis:
    image: redis:alpine
    container_name: redis
    ports: 
      - 16379:6379
    networks:
      - back-tier

  postgres:
    image: sameersbn/postgresql:9.6-2
    container_name: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - 15432:5432
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  airflow:
    image: puckel/docker-airflow:1.8.1
    container_name: airflow
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
    volumes:
      - ./airflow/dags:/usr/local/airflow/dags
    ports:
      - "18080:8080"
    command: webserver 
    networks:
      - back-tier
 
volumes:
  postgres-data:

networks:
  back-tier: